//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fun", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string fun(string user1, string pass1, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fun", ReplyAction="*")]
        System.Threading.Tasks.Task<string> funAsync(string user1, string pass1, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string login(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<string> loginAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/result", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable result(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/result", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> resultAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool insertResult(string name, string s1, string s2, string s3, string s4, string s5, string s6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertResult", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> insertResultAsync(string name, string s1, string s2, string s3, string s4, string s5, string s6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/edit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool edit(int id, string name, string s1, string s2, string s3, string s4, string s5, string s6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/edit", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> editAsync(int id, string name, string s1, string s2, string s3, string s4, string s5, string s6);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Project.ServiceReference2.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Project.ServiceReference2.WebServiceSoap>, Project.ServiceReference2.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string fun(string user1, string pass1, string name) {
            return base.Channel.fun(user1, pass1, name);
        }
        
        public System.Threading.Tasks.Task<string> funAsync(string user1, string pass1, string name) {
            return base.Channel.funAsync(user1, pass1, name);
        }
        
        public string login(string user, string pass) {
            return base.Channel.login(user, pass);
        }
        
        public System.Threading.Tasks.Task<string> loginAsync(string user, string pass) {
            return base.Channel.loginAsync(user, pass);
        }
        
        public System.Data.DataTable result(int id) {
            return base.Channel.result(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> resultAsync(int id) {
            return base.Channel.resultAsync(id);
        }
        
        public bool insertResult(string name, string s1, string s2, string s3, string s4, string s5, string s6) {
            return base.Channel.insertResult(name, s1, s2, s3, s4, s5, s6);
        }
        
        public System.Threading.Tasks.Task<bool> insertResultAsync(string name, string s1, string s2, string s3, string s4, string s5, string s6) {
            return base.Channel.insertResultAsync(name, s1, s2, s3, s4, s5, s6);
        }
        
        public bool delete(int id) {
            return base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
        
        public bool edit(int id, string name, string s1, string s2, string s3, string s4, string s5, string s6) {
            return base.Channel.edit(id, name, s1, s2, s3, s4, s5, s6);
        }
        
        public System.Threading.Tasks.Task<bool> editAsync(int id, string name, string s1, string s2, string s3, string s4, string s5, string s6) {
            return base.Channel.editAsync(id, name, s1, s2, s3, s4, s5, s6);
        }
    }
}
